### ISSUE TITLE
Использование os.path.join приводит к ошибке 404 в среде Windows

### ISSUE THREAD

**Issue by Playermet** [myback/docker_pull#3]
При попытке скачивания образом скриптом в Windows возникает ошибка 404. Например:
```
python docker_pull.py redis:7.2.3
latest: Pulling from redis
ERROR:root:Status code: 404, Response: b'404 page not found\n'
...
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://registry-1.docker.io/v2/library%5Credis/manifests/latest
```
Проблемой является обратный слеш (%5C) вместо прямого в URL. При замене os.path.join в ImageParser:_url на конкатенацию с прямым слешем скрипт отрабаетыват штатно.

**Comment by myback** [comment]
Спасибо за ошибку. Добавил поддержку Windows
